version: '3.9'

services:
  backend:
    build: .
    command: >
      python3 app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "1586:8000"
    depends_on:
      - frontend

  frontend:
    working_dir: /app/frontend
    image: node:20
    volumes:
      - ./app/frontend:/app/frontend
    ports:
      - "3000:3000"
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
